# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

T_nC <- function(r, n1, YY, m) {
    .Call('_SA23204177_T_nC', PACKAGE = 'SA23204177', r, n1, YY, m)
}

#' @title Testing of mean vector using Rcpp and RcppEigen
#' @description Testing of mean vector using Rcpp and RcppEigen
#' @param sam the matrix of samples
#' @param m trimming parameter
#' @param n sample size
#' @return \code{TRUE} (reject null hypothesis) or \code{FALSE}
#' @examples
#' \dontrun{
#' library(MASS)
#' set.seed(1234)
#' n1 <- n2 <- 50
#' p <- 200
#' mu1 <- rep(0, p)
#' mu2 <- mu1
#' mu2[1:10] <- 1
#' true.cov <- 0.4^(abs(outer(1:p, 1:p, "-"))) # AR1 covariance
#' sam1 <- mvrnorm(n = n1, mu = mu1, Sigma = true.cov)
#' sam2 <- mvrnorm(n = n2, mu = mu2, Sigma = true.cov)
#' Wang2020C(sam1, m=5, n=n1)
#' Wang2020C(sam2, m=5, n=n2)
#' }
#' @export
Wang2020C <- function(sam, m, n) {
    .Call('_SA23204177_Wang2020C', PACKAGE = 'SA23204177', sam, m, n)
}

